### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by alexborisewich**
1.Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-2/rs-lang/rslang.md
2.Done 22.08.2022
3. Functional requirements
Create application layout

### CODE REVIEW

**Review by Axe11er — APPROVED** [review]
thanks, files ready for merge

**Comment by PiachkoAliaksey** [comment]
thanks, files ready for merge

**Review by PiachkoAliaksey — COMMENTED** [review]
code is workable, ready for merge

**Review by PiachkoAliaksey — APPROVED** [review]
files ready for merge

**Pull request merged**
